version: '3.8'
services:
  info-service:
    build: ./info-service
    container_name: info-service
    ports:
      - "8080:8080"
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - info-service
  forward-proxy:
    build: ./forward-proxy
    container_name: forward-proxy
    ports:
      - "3128:3128"